"""SuppColImage

Revision ID: 2c6547b82742
Revises: 0f80e7269c49
Create Date: 2020-05-22 00:24:00.589533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6547b82742'
down_revision = '0f80e7269c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
