"""remove column title

Revision ID: 8c8df735ce3c
Revises: 23fae49a7e31
Create Date: 2020-05-20 17:26:59.954764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8df735ce3c'
down_revision = '23fae49a7e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editor', sa.Column('title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editor', 'title')
    # ### end Alembic commands ###
